// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestApiDemo.Infrastructure.Data;

namespace RestApiDemo.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211122061347_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RestApiDemo.DomainCore.Models.Resource.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("RestApiDemo.DomainCore.Models.Resource.ResourceContent", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ResourceId")
                        .HasColumnType("int");

                    b.Property<string>("Val")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.HasIndex("ResourceId");

                    b.ToTable("ResourceContent");
                });

            modelBuilder.Entity("RestApiDemo.DomainCore.Models.Resource.ResourceContent", b =>
                {
                    b.HasOne("RestApiDemo.DomainCore.Models.Resource.Resource", null)
                        .WithMany("ResourceContents")
                        .HasForeignKey("ResourceId");
                });

            modelBuilder.Entity("RestApiDemo.DomainCore.Models.Resource.Resource", b =>
                {
                    b.Navigation("ResourceContents");
                });
#pragma warning restore 612, 618
        }
    }
}
